DBT Plugin Enhancements PI07 - Dbt- Vertica 1.8.5
vertica/dbt-vertica pull request #138
Opened 2024-08-20 06:39 UTC by mkottakota1

PR Request for merging the changes for dbt-core 1.8.5 & dbt-vertica adapter 1.8.5

2024-08-20 06:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vertica/dbt-vertica?pullRequest=138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vertica/dbt-vertica?pullRequest=138) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vertica/dbt-vertica?pullRequest=138) it.</sub>

2024-08-22 03:13 UTC, ajay-abrol2 commented on dbt/include/vertica/macros/utils/safe_cast.sql
> +        try_to_geometry({{field}})
Is this function from Vertica DB?

2024-08-22 03:13 UTC, ajay-abrol2 commented on dbt/include/vertica/macros/utils/safe_cast.sql
> +        try_to_geography({{field}})
Is this function of Vertica DB?

2024-08-22 03:16 UTC, ajay-abrol2 commented on tests/functional/adapter/unit_testing/test_case_insenstivity.py
> +class TestPosgresUnitTestCaseInsensitivity(BaseUnitTestCaseInsensivity):
rename this testcase as per Vertica

2024-08-22 03:17 UTC, ajay-abrol2 commented on tests/functional/adapter/unit_testing/test_types.py
> +class TestPostgresUnitTestingTypes(BaseUnitTestingTypes):
Rename

2024-08-22 03:19 UTC, ajay-abrol2 requested changes
I have reviewed and added few minor comments.

2024-08-22 09:30 UTC, mkottakota1 commented on dbt/include/vertica/macros/utils/safe_cast.sql
> +        try_to_geography({{field}})
Removed this function, it's not applicable for Vertica

2024-08-22 09:31 UTC, mkottakota1 commented
Done the needul

2024-09-16 08:55 UTC, closed without merging