add params for create schema
vertica/dbt-vertica pull request #22
Opened 2022-03-19 16:01 UTC by barloc

Hello.

We need some parameters before creating models in vertica for better working of our queries.
So we propose some parameters for models:

- order_by_string - string of order by columns ("col1,col2,col3")
- segmented_by_string - string of segmented by columns ("col1")
- partition_by_string - string of partition by columns ("EXTRACT(YEAR FROM col1)*10000 + EXTRACT(MONTH FROM col1)*100")

And set KSAFE = 0 for all models, if database is "docker", because it use for development, and KSAFE = 1 in other.

2022-03-21 16:08 UTC, barloc commented
Hello.
This is official doc - https://www.vertica.com/docs/11.1.x/HTML/Content/Authoring/SQLReferenceManual/Statements/CREATETABLE.htm

'order by' is about indexing in vertica and effective storing data on disks.
'segmented by' is key for splitting of data batch to the current node.
'partition by' is about delete or archive old data.
ksafe is replication factor for vertica.

2022-03-21 18:33 UTC, ahedengren commented
Hi @barloc ,

I was more thinking towards our docs so we can explain how to use the functionality.

Question: have you written any tests for this to make sure it works, and it won't accidently break if we refactor anything?

2022-03-23 14:31 UTC, andyreagan commented
The `KSAFE` parameter shouldn't be hardcoded as 0 or 1 based on the database name. This should be an option just like the others.

We definitely need a test to go along with this.

2022-03-23 14:33 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if order_by_string is not none and not temporary -%}
Shouldn't `none` be capitalized? I think this has to be valid python, so `None`

2022-03-23 14:34 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if segmented_by_string is not none and order_by_string is not none and not temporary -%}
Is it really necessary to use `order by` in order to use `segment by`?

2022-03-23 14:36 UTC, andyreagan requested changes

2022-03-23 14:36 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  all nodes ksafe{% if database is not none and "docker" in database %} 0 {% else %} 1 {% endif %}
This need to be updated. Some users do not have permissions to set KSAFE parameters, in which case this can't be hardcoded to set a particular value.

2022-03-23 14:36 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if partition_by_string is not none and segmented_by_string is not none and not temporary -%}
Again, do you have have to specify `segment by` to use `partition by`?

2022-03-23 14:36 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  group by {{ partition_by_string }}
why the `group by` here?

2022-03-23 14:39 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if segmented_by_string is not none and order_by_string is not none and not temporary -%}
based on Vertica 11.x docs, you don't _need_ to use `order by` to use a segmentation clause, so line 18 here should be:

```
{% if segmented_by_string is not none not temporary -%}
```

2022-03-23 14:42 UTC, andyreagan commented
I also see that you're checking that these tables aren't temporary in many cases here, which isn't necessary in each case.

Temporary tables seem to allow segmentation, ordering, ksafe. They don't allow partition clause. Even in the latter case, should we be protecting the user from themselves here?

2022-03-23 14:44 UTC, ahedengren commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if order_by_string is not none and not temporary -%}
Jinja uses lowercase `none` though supports `None`.

https://jinja.palletsprojects.com/en/3.0.x/templates/#expressions

2022-03-23 14:46 UTC, andyreagan commented
I realize this is a lot of questions.

I think this would be a great addition, to fully utilize table optimization on Vertica. However, we need to get this right!

2022-03-23 14:47 UTC, ahedengren commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if segmented_by_string is not none and order_by_string is not none and not temporary -%}
The table could also be unsegmented all nodes as well. Smaller dimensional tables benefit from that.

2022-03-23 14:48 UTC, andyreagan commented
One more thought: you're allowing these to be set by strings, when really they are often lists of columns. Rather than the user setting `col1,col2`, they should be able to use a list instead.

2022-03-23 15:00 UTC, barloc commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if order_by_string is not none and not temporary -%}
Hello.
Option for KSAFE is not convenient i think.
Usually in vertica cluster we have KSAFE = 1, but if we go to dev env, and start vertica in docker - KSAFE 1 brokes all code in DBT :(

2022-03-23 15:05 UTC, andyreagan commented
the other option, if this isn't handled by dbt, is to first create the table before dbt runs and force dbt to insert into them rather than build the tables (incremental). I don't really like that, since dbt creating tables is a big part of what it's doing.

you could also argue that this can just be handled by creating appropriate projections outside of dbt. however, that's imposing a lot of work when dbt could just do these table-level optimizations while it runs.

2022-03-23 15:07 UTC, andyreagan commented
one more thing - we would need to check that the table is not being created a view.

a neat concept that I haven't tried yet, but plan to, is forcing dbt to build everything as views in a different schema just to validate the sql syntax, before building the actual data pipeline.

2022-03-23 15:09 UTC, ahedengren commented
That is true. A large part of dbt is that a lot of the DDL is hidden behind the scenes. Just a fine line on where to draw this. Perhaps it's on a what makes sense. I do think they are value adding additions, of course it's important to need to challenge ideas 

> the other option, if this isn't handled by dbt, is to first create the table before dbt runs and force dbt to insert into them rather than build the tables (incremental). I don't really like that, since dbt creating tables is a big part of what it's doing.
> 
> you could also argue that this can just be handled by creating appropriate projections outside of dbt. however, that's imposing a lot of work when dbt could just do these table-level optimizations while it runs.

2022-03-23 15:11 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if order_by_string is not none and not temporary -%}
what I'm saying for KSAFE is that we should not set it at 0 or 1, but allow the user to specify. 

how you set that yourself...you can then manage. e.g., you can set the KSAFE option from your own settings based on environment.

2022-03-23 15:12 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if partition_by_string is not none and segmented_by_string is not none and not temporary -%}
the answer is no, you don't.

2022-03-23 15:13 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  group by {{ partition_by_string }}
okay, so group by is an option on partitioning, but it's not required. should be it's own option.

2022-03-23 15:14 UTC, andyreagan commented on dbt/include/vertica/macros/materializations/models/table/create_table_as.sql
> +  {% if order_by_string is not none and not temporary -%}
I'm going to close this particular convo on the `none`/`None`... TIL!

2022-09-26 17:52 UTC, closed without merging

2022-09-26 17:53 UTC, andyreagan commented
I reopened this, with nearly identical code as https://github.com/vertica/dbt-vertica/pull/39